### ISSUE TITLE
socat does not work (again!)

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/ci_cd#11]
I have tested again the RTE deployment.

- tested Etherbone locally (eb-mon -v) -> ok
- tested saftlib locally (saft-ctl -fijs, snoop, inject ,...) -> ok

- tested Etherbone remotely eb-ls tcp/fec0815.acc -> failed

**Comment by alex-cscotg** [comment]
reference SCU? 0097?

**Comment by dietrichb** [comment]
yep... (tried both: RC8 and R8), same result....

**Comment by bradomyn** [comment]
fixed

The IT group has updated something in the clusters and it breaks our building process.

**Comment by bradomyn** [comment]
it was not the IT, it is an automatic updates of the RPM repos that we're using.... it means that we are working
with moving targets! great for testing and robust development!!!
