### ISSUE TITLE
Timing RTE on ASL "Admin Edition"

### ISSUE THREAD

**Issue by alex-cscotg** [GSI-CS-CO/ci_cd#19]
What we need:

- dm-cmd + dm-sched + library
- eb-massmon
- eb-w1-write (commissioning)
- missing eb-tools

**Comment by alex-cscotg** [comment]
- uTCA tools (?)

**Comment by dietrichb** [comment]
* stuff for commissioning of all TRs
* stuff for TOS on-call service

==> is this one or two special RTE editions?

**Comment by alex-cscotg** [comment]
Should be one edition.

**Comment by alex-cscotg** [comment]
- onewire-scanner (commissioning and testing)

**Comment by dietrichb** [comment]
for on-call service
* dmunipz-ctl 
* wr-mil-gw-ctl
might be handy too

**Comment by stefanrauch** [comment]
eb-iflash

**Comment by alex-cscotg** [comment]
shell aliases...

alias ll='ls -alF'

**Comment by alex-cscotg** [comment]
busctl (dbus control from shell)

**Comment by alex-cscotg** [comment]
Available for testing:

Setting(s):
lrwxrwxrwx   1 x  y     date 10_timing_backdoor -> ../global/timing_backdoor
lrwxrwxrwx   1 x  y     date 20_timing-rte -> ../global/timing-rte-tg-nightly-admin

You need to send me your SSH public key (timing_backdoor), otherwise you won't be able to log in.
