### ISSUE TITLE
timing-rte.sh: reset statistics for eCPU stalls and WR time continuity

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/ci_cd#25]
After all stuff in timing-rte.sh has finished, it is necessary to initialize the 'DM-Diagnostics' slave properly. For each TR, the following code shall be executed.

eb-mon dev/wbmN wrstatreset 8 50000

Consider adding the following line at the end of the script

for dev in /dev/wbm*; do eval eb-mon ${dev#/} wrstatreset 8 50000; done

**Comment by alex-cscotg** [comment]
Will be part of Enigma-V5.0.3. See commit bb8d719.
