### ISSUE TITLE
copy monitoring tool too...

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/ci_cd#4]
in case monitoring tool wr-mon shall be present in runtime system too, the script for deployment (.../ci_cd/scripts/deployment/RTE_Timing/build-rte.sh) has to be changed:

In my workspace, I have added one line to fix this.
$ git diff build-rte.sh
diff --git a/scripts/deployment/RTE_Timing/build-rte.sh b/scripts/deployment/RTE_Timing/build-rte.sh
index 5310f51..5969f07 100755
--- a/scripts/deployment/RTE_Timing/build-rte.sh
+++ b/scripts/deployment/RTE_Timing/build-rte.sh
@@ -2,14 +2,14 @@
...
 # Clean up installation folders
@@ -74,6 +74,7 @@ make -j $JOBS
 for i in flash console info sflash time; do
   cp eb-$i $RTE_DIR/bin
 done
+cp monitoring/wr-mon $RTE_DIR/bin

**Comment by bradomyn** [comment]
Ok, no problem. Create a branch, commit, and merge.

**Comment by dietrichb** [comment]
done -> closed
