### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by alex-cscotg** [GSI-CS-CO/ci_cd#5]
Do we still need these branches here?

@dietrichb:
tools_dietrich-2016-11-22 (even with master)

@bradomyn:
rc8_arguments 
rc8

**Comment by dietrichb** [comment]
tools_dietrich-2016-11-22 deleted

--> closed

**Comment by alex-cscotg** [comment]
Reopened, there are still old branches from @bradomyn  :crying_cat_face:

**Comment by bradomyn** [comment]
we need the branches, we are goin to use them for C* release
