### ISSUE TITLE
access via socat does not work

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/ci_cd#6]
It was reported, that access via socat no longer works. It was suggested that this is due to a missing kerberos library.

**Comment by alex-cscotg** [comment]
Additional information:

This configuration works fine:

```

#xxx@asl730:/common/export/nfsinit/scuxl0097 $ ll
10_timing_backdoor -> ../global/timing_backdoor
20_timing-rte -> ../global/timing-rte-RC8-balloon_0
```


This configuration doesn't work:

```

#xxx@asl730:/common/export/nfsinit/scuxl0097 $ ll
10_timing_backdoor -> ../global/timing_backdoor
20_timing-rte -> ../global/timing-rte-R8-balloon_0
```

Maybe we should look into this together?

**Comment by bradomyn** [comment]
Ok, sure. Stefan tested also with RC8 and no with R8.

2016-11-24 10:22 GMT+01:00 alex-cscotg <notifications@github.com>:

**Comment by bradomyn** [comment]
I have created the branch fixing_socat where I have added directly the kerberos lib.

I also removed the standard target /comon/exports .... and replaced with /dev/null
so we don't have unintentional overwriting....

Please check the branch and tell me if it works for you, for me it works...

**Comment by bradomyn** [comment]
stop, I found another problem...

**Comment by dietrichb** [comment]
hm..., I already tried on a SCU
- access via socat ok
- wr-mon works -> eb, driver... ok
- saft-ctl works -> saftlib... ok

**Comment by bradomyn** [comment]
ok, now it should work, I tested removing all the folders. I have also tested with an SCU and everything is there:
access via socat ok
wr-mon works -> eb, driver... ok
saft-ctl works -> saftlib... ok

please check also with a VME

**Comment by bradomyn** [comment]
please check in branch: fixing_socat

**Comment by miree** [comment]
I tested a VETAR2A (kp1cx03) with symlink
`20_timing-rte -> ../global/timing-rte-R8-balloon_0`

`wr-mon -t0 tcp/kp1cx03.acc.gsi.de`    **works**
`saft-ctl baseboard -j` **works** (with `saftd baseboard:tcp/kp1cx03.acc.gsi.de`)

**Comment by dietrichb** [comment]
tested with SCU:
- socat ok
- wr-mon ok
- saft-ctl ok

**Comment by bradomyn** [comment]
done
