### ISSUE TITLE
feature request: autogenerate build info for build and deployment

### ISSUE THREAD

**Issue by dietrichb** [GSI-CS-CO/ci_cd#7]
When building and deploying with https://github.com/GSI-CS-CO/ci_cd/blob/master/scripts/deployment/RTE_Timing/build-rte.sh, it would be great to autogenerate build information. Maybe in "timing-rte_buildinfo"? This would be helpful in
- tracing back what repository status the build is based on
- building again the same thing at a later time
- post-mortem in case of runtime trouble
- ...

Suggest to include the following
- username
- date/time
- machine
- OS/Kernel
- name of script
- ci_cd:
-- URL to repository
-- branch
-- SHA
-- dirty flag
- bel_projects:
-- URL to repository
-- branch
-- SHA
-- dirty flag

Would it make sense to copy that info to the runtime systems too? Suggest to copy to /etc, similar to "os-release".

**Comment by bradomyn** [comment]
It creates now a log file of the compilation e.g. RTE_log_25-11-2016_19-01-14

and the "timing-rte_buildinfo" placed in /etc/ with all the information suggested.

please check in branch: fixing_socat

**Comment by dietrichb** [comment]
Two minor issues
- typo: derty -> dirty; fixed and pushed to branch fixing_socat
- as one must modify the build script (build path), the cd_cd repo is always reported dirty

**Comment by bradomyn** [comment]
done
